#! /bin/sh

dunst &
killall polybar &
picom --experimental-backends &
nitrogen --restore &
/home/dexter/.screenlayout/t.sh &
/home/dexter/.config/polybar/launchpoly.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
bspc monitor DP-4 -d I II III IV V VI VII VIII IX X
bspc monitor DP-0 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

bspc config bottom_padding       0
bspc config top_padding          0
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

